#ifndef SHARED_MAINTENANCE_CONFIG_H
#define SHARED_MAINTENANCE_CONFIG_H

// ---------------- MAINTENANCE COUNTER ----------------
#define MAINTENANCE_INTERVAL_DAYS        0UL
#define MAINTENANCE_INTERVAL_HOURS       0UL
#define MAINTENANCE_INTERVAL_MINUTES     1UL

#endif
